version: "3.8"

services:
  nginx:
    # Image comes from here: https://hub.docker.com/_/nginx
    image: nginx:1.21.6-alpine
    volumes:
      # Mount the local directory shared_files into the container
      - ./shared_files:/usr/share/nginx/html
      # Mount the config file nginx.conf into the container
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      # Map port 80 inside the container to port 8000 on your local machine
      - 8000:80
